LocDVD\APIBundle\Entity\Actor:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        actor:
            expose: true
        mapper:
            expose: true
        createDate:
            expose: true
        modifyDate:
            expose: true