LocDVD\APIBundle\Entity\Tvshow:
    exclusion_policy: ALL
    properties:
        title:
            expose: true
        year:
            expose: true
        originallyAvailable:
            expose: true
