LocDVD\APIBundle\Entity\TvshowEpisode:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        tvShow:
            expose: true
        mapper:
            expose: true
        tagLine:
            expose: true
        year:
            expose: true
        originallyAvailable:
            expose: true
        tvshow:
            expose: true
        season:
            expose: true
        episode:
            expose: true
        originallyAvailable:
            expose: true
        createDate:
            expose: true
        modifyDate:
            expose: true
        certificate:
            expose: true


