loc_dvdapi:
    resource: "@LocDVDAPIBundle/Controller/"
    type:     annotation
    prefix:   /

users:
    type:   rest
    resource:   LocDVD\APIBundle\Controller\MovieController

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    

