loc_dvdapi:
    resource: "@LocDVDAPIBundle/Controller/"
    type:     annotation
    prefix:   /

truc:
    type:   rest
    resource :  LocDVD\APIBundle\Controller\UpdateController

movies:
    type:   rest
    resource:   LocDVD\APIBundle\Controller\MovieController

actors:
    type:   rest
    resource:   LocDVD\APIBundle\Controller\ActorController

search:
    type:   rest
    resource:   LocDVD\APIBundle\Controller\SearchController

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    

