loc_dvdapi:
    resource: "@LocDVDAPIBundle/Controller/"
    type:     annotation
    prefix:   /

movies:
    type:   rest
    resource:   LocDVD\APIBundle\Controller\MovieController

actors:
    type:   rest
    resource:   LocDVD\APIBundle\Controller\ActorController

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    

